// Pure-TS unit tests for the fingerprint similarity engine.
// Runs under: tsx --test packages/crawler/__tests__/fingerprint.test.ts

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  computeTextShape,
  similarity,
  pickStableAttrs,
  type ElementSignature,
} from "../lib/fingerprint.js";

function sig(overrides: Partial<ElementSignature> = {}): ElementSignature {
  return {
    tag: "li",
    classes: ["lLd3Je"],
    attrs: { "data-test": "card" },
    textShape: "w w9 wp w w wp w",
    depth: 4,
    siblingIndex: 0,
    childTagCounts: { div: 1, a: 1 },
    ancestorChain: ["ul", "main", "body", "html"],
    ...overrides,
  };
}

test("computeTextShape collapses letters, digits, whitespace, punct", () => {
  assert.equal(computeTextShape("Hello World 123!"), "w w 9p");
  assert.equal(computeTextShape(""), "");
  assert.equal(computeTextShape("   "), " ");
});

test("computeTextShape redacts PII-shaped strings", () => {
  // A real name and a generic name produce the same shape — PII safe.
  const a = computeTextShape("Madhan Kumar Govindu");
  const b = computeTextShape("Alice Bob Carlson");
  assert.equal(a, b);
  // Shape uses only category tokens (w, 9, p, space) — original text
  // never survives. Verify the original words are absent.
  assert.ok(!a.includes("Madhan") && !a.includes("Alice"));
  // Shape is very short (collapsed runs) and contains only tokens.
  assert.ok(/^[w9p ]+$/.test(a), `shape should only contain w/9/p/space, got: ${a}`);
});

test("computeTextShape caps length", () => {
  const huge = "a".repeat(500) + "1".repeat(500);
  const shape = computeTextShape(huge);
  assert.ok(shape.length <= 80);
});

test("similarity returns 1 for identical signatures", () => {
  const s = sig();
  assert.equal(similarity(s, s), 1);
});

test("similarity returns 0 for different tags", () => {
  assert.equal(similarity(sig({ tag: "div" }), sig({ tag: "li" })), 0);
});

test("similarity stays above 0.6 with one renamed class", () => {
  // Realistic drift: career site shipped a hashed CSS module rename.
  const before = sig({ classes: ["lLd3Je"] });
  const after = sig({ classes: ["abc123_card"] });
  const s = similarity(before, after);
  assert.ok(s >= 0.6, `expected >=0.6, got ${s}`);
});

test("similarity drops below 0.4 when both class + ancestor change", () => {
  const before = sig();
  const after = sig({
    classes: ["completely_different"],
    ancestorChain: ["section", "article", "div", "body"],
  });
  const s = similarity(before, after);
  assert.ok(s < 0.55, `expected <0.55, got ${s}`);
});

test("similarity penalizes wrong child-tag bag", () => {
  const before = sig();
  const after = sig({ childTagCounts: { img: 5 } });
  const baseline = similarity(before, sig());
  const dropped = similarity(before, after);
  assert.ok(dropped < baseline);
});

test("pickStableAttrs filters volatile ids and keeps data-/aria-/role", () => {
  const out = pickStableAttrs({
    id: "header",
    role: "listitem",
    "data-test": "card",
    "aria-label": "Job listing",
    class: "lLd3Je",
    style: "color:red",
    "ng-reflect-router-link": "/jobs/1",
  });
  assert.deepEqual(out, {
    id: "header",
    role: "listitem",
    "data-test": "card",
    "aria-label": "Job listing",
  });
});

test("pickStableAttrs drops autogenerated nonce ids", () => {
  const out = pickStableAttrs({ id: "f3a8b1c4d2e0" });
  assert.equal(out.id, undefined);
});
