// Curated facts about each of the 18 product companies ProdMatch tracks.
//
// Purpose: every public surface (homepage, /companies, /cities, /skills,
// /salaries) needs to render useful content even when the daily crawler
// hasn't populated the jobs table yet. This module supplies the static
// truth that's always-true: HQ, founded year, what the company does,
// India hubs they operate in, role functions they hire for, typical
// tech stack, and reference salary bands.
//
// Editorial integrity: every salary band carries a "reference" qualifier
// and is sourced from publicly-known patterns (engineering blogs,
// disclosed JDs ProdMatch has seen historically, Glassdoor/levels.fyi
// medians). NOT precise per-month figures — these are calibrated bands
// the page can show in the absence of live JD data.

import type { CanonicalRoleFunction } from "@prodmatch/shared";

export interface ReferenceBand {
  seniority: string;
  /** Reference low — base only, INR LPA. */
  refLowLpa: number;
  /** Reference high — base only, INR LPA. */
  refHighLpa: number;
  /** TC includes variable + stock typical multiplier. */
  refTcLowLpa: number;
  refTcHighLpa: number;
}

export interface CompanyFacts {
  slug: string;
  /** Full legal / display name. */
  name: string;
  /** Short type label — for the hero pill on company pages. */
  kind: "Big Tech" | "Fintech" | "Consumer-Tech" | "Enterprise SaaS" | "E-commerce";
  /** 1-sentence what-they-do — for the listing card subline. */
  oneLiner: string;
  /** 2-3 paragraph overview for the company landing page. */
  overview: string;
  /** Global HQ city — used in schema.org + the Stats strip. */
  hqCity: string;
  /** Country (ISO label, used in schema.org). */
  hqCountry: string;
  /** Year founded. */
  founded: number;
  /** Official career-page URL. */
  careersUrl: string;
  /** Primary India hubs where they actively hire (subset of INDIA_HUBS). */
  indiaHubs: string[];
  /** Role functions they actively hire across (canonical keys). */
  roleFunctions: CanonicalRoleFunction[];
  /** Typical tech stack signal (12-20 entries, casual order). */
  typicalStack: string[];
  /** Reference salary bands per seniority — used when live JDs disclose nothing. */
  referenceBands: ReferenceBand[];
}

const COMMON_ROLES: CanonicalRoleFunction[] = [
  "backend", "frontend", "fullstack", "data_engineering", "ml_ai",
  "devops_platform", "mobile", "qa_sdet", "product_management",
];

const FAANG_BANDS: ReferenceBand[] = [
  { seniority: "SDE-1 / Junior",   refLowLpa: 18, refHighLpa: 26, refTcLowLpa: 25, refTcHighLpa: 45 },
  { seniority: "SDE-2 / Mid",      refLowLpa: 28, refHighLpa: 42, refTcLowLpa: 45, refTcHighLpa: 75 },
  { seniority: "SDE-3 / Senior",   refLowLpa: 42, refHighLpa: 60, refTcLowLpa: 75, refTcHighLpa: 110 },
  { seniority: "Staff / Lead",     refLowLpa: 60, refHighLpa: 85, refTcLowLpa: 110, refTcHighLpa: 170 },
  { seniority: "Principal",        refLowLpa: 85, refHighLpa: 130, refTcLowLpa: 170, refTcHighLpa: 280 },
];

const INDIA_UNICORN_BANDS: ReferenceBand[] = [
  { seniority: "SDE-1 / Junior",   refLowLpa: 12, refHighLpa: 18, refTcLowLpa: 14, refTcHighLpa: 24 },
  { seniority: "SDE-2 / Mid",      refLowLpa: 18, refHighLpa: 32, refTcLowLpa: 22, refTcHighLpa: 40 },
  { seniority: "SDE-3 / Senior",   refLowLpa: 28, refHighLpa: 48, refTcLowLpa: 34, refTcHighLpa: 60 },
  { seniority: "Staff / Lead",     refLowLpa: 45, refHighLpa: 70, refTcLowLpa: 55, refTcHighLpa: 95 },
  { seniority: "Principal",        refLowLpa: 65, refHighLpa: 95, refTcLowLpa: 80, refTcHighLpa: 130 },
];

const FINTECH_BANDS: ReferenceBand[] = [
  { seniority: "SDE-1 / Junior",   refLowLpa: 14, refHighLpa: 22, refTcLowLpa: 16, refTcHighLpa: 28 },
  { seniority: "SDE-2 / Mid",      refLowLpa: 22, refHighLpa: 38, refTcLowLpa: 26, refTcHighLpa: 48 },
  { seniority: "SDE-3 / Senior",   refLowLpa: 35, refHighLpa: 55, refTcLowLpa: 42, refTcHighLpa: 70 },
  { seniority: "Staff / Lead",     refLowLpa: 50, refHighLpa: 80, refTcLowLpa: 65, refTcHighLpa: 110 },
  { seniority: "Principal",        refLowLpa: 75, refHighLpa: 110, refTcLowLpa: 95, refTcHighLpa: 160 },
];

export const COMPANY_FACTS: readonly CompanyFacts[] = [
  {
    slug: "google",
    name: "Google",
    kind: "Big Tech",
    oneLiner: "Search, ads, cloud, Android, YouTube — global tech across product surfaces.",
    overview: "Google's India engineering presence includes Bengaluru, Hyderabad, and Gurugram offices working across Search, Ads, Android, Cloud (GCP), YouTube, Maps and Workspace. India teams contribute to globally-deployed products — the bar matches Mountain View. Hiring loops emphasise structured DSA + system design + Googleyness rounds; comp follows the global L-band template (L3-L6 most common in India).",
    hqCity: "Mountain View, CA",
    hqCountry: "United States",
    founded: 1998,
    careersUrl: "https://www.google.com/about/careers/applications/jobs/results?location=India",
    indiaHubs: ["Bengaluru", "Hyderabad", "Gurugram"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design", "program_management"],
    typicalStack: ["Java", "Go", "Python", "C++", "Kubernetes", "BigQuery", "Spanner", "TensorFlow", "Bigtable", "Borg", "Protobuf", "gRPC"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    kind: "Big Tech",
    oneLiner: "Azure, Office, GitHub, Windows, AI — enterprise + consumer at global scale.",
    overview: "Microsoft India has major engineering centres in Hyderabad (largest outside Redmond) and Bengaluru, plus a Gurugram office. Teams work across Azure, Microsoft 365, GitHub, Bing/AI Search, Windows, and the Office stack. Hiring loops follow the standard Microsoft template — 4-5 rounds combining DSA, system design, and 'as appropriate' behavioural rounds. The 'Customer obsession + One Microsoft' value rubric is real and shows up in behavioural scoring.",
    hqCity: "Redmond, WA",
    hqCountry: "United States",
    founded: 1975,
    careersUrl: "https://careers.microsoft.com/v2/global/en/search?lc=India",
    indiaHubs: ["Hyderabad", "Bengaluru", "Gurugram", "Noida"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design", "program_management"],
    typicalStack: ["C#", ".NET", "TypeScript", "Azure", "Kubernetes", "PowerShell", "Cosmos DB", "Bicep", "React", "Python"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "meta",
    name: "Meta",
    kind: "Big Tech",
    oneLiner: "Facebook, Instagram, WhatsApp, Reality Labs — global consumer + AR/VR.",
    overview: "Meta's India engineering footprint is centred on Bengaluru (and a smaller Hyderabad presence), working primarily on Reality Labs, infrastructure, ads, and parts of WhatsApp + Instagram. Engineering loops follow Meta's standard E3-E7 template — 4-5 rounds with sharp DSA + product-design + behavioural rounds. The 'move fast + impact' rubric is real in behavioural scoring; explicit metrics + scope matter.",
    hqCity: "Menlo Park, CA",
    hqCountry: "United States",
    founded: 2004,
    careersUrl: "https://www.metacareers.com/jobs/?offices[0]=India",
    indiaHubs: ["Bengaluru", "Hyderabad"],
    roleFunctions: ["backend", "frontend", "fullstack", "ml_ai", "data_engineering", "devops_platform", "mobile", "product_management", "design"],
    typicalStack: ["PHP/Hack", "Python", "C++", "React", "GraphQL", "Cassandra", "PyTorch", "Presto", "Bento ML", "Buck2"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "amazon",
    name: "Amazon",
    kind: "Big Tech",
    oneLiner: "AWS, retail, Prime Video, Alexa, devices — broadest scope across all 18.",
    overview: "Amazon India has the largest single engineering footprint of any product company in India — Bengaluru (HQ for India tech), Hyderabad, Chennai, Pune, Delhi NCR. Teams work across AWS, Retail, Prime Video, Alexa, and dozens of internal platforms. Hiring loops are explicitly Amazon — 4-6 rounds with strong Leadership Principles emphasis throughout (every interviewer scores LPs, not just behavioural). Bar Raiser owns the final call.",
    hqCity: "Seattle, WA",
    hqCountry: "United States",
    founded: 1994,
    careersUrl: "https://www.amazon.jobs/en/search?base_query=&loc_query=India",
    indiaHubs: ["Bengaluru", "Hyderabad", "Chennai", "Pune", "Delhi NCR"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "program_management"],
    typicalStack: ["Java", "Python", "AWS", "DynamoDB", "Lambda", "S3", "EKS", "TypeScript", "React", "C++", "Rust"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "apple",
    name: "Apple",
    kind: "Big Tech",
    oneLiner: "iPhone, iOS, services, silicon, retail — tightly-integrated consumer hardware + software.",
    overview: "Apple India engineering is centred on Hyderabad (Apple Service Centre + maps + iCloud teams) and Bengaluru (smaller). India hiring is relatively limited compared to Microsoft / Google / Amazon — but the bar is exceptionally high. Loops emphasise deep technical mastery in narrower domains (iOS, audio, silicon, services). Behavioural rounds favour craft-obsession + secrecy + cross-functional collaboration.",
    hqCity: "Cupertino, CA",
    hqCountry: "United States",
    founded: 1976,
    careersUrl: "https://jobs.apple.com/en-in/search?location=india-INDC",
    indiaHubs: ["Hyderabad", "Bengaluru"],
    roleFunctions: ["backend", "ml_ai", "mobile", "devops_platform", "qa_sdet"],
    typicalStack: ["Swift", "Objective-C", "C++", "Python", "Metal", "Core ML", "Foundation", "AppKit", "Combine", "SwiftUI"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "atlassian",
    name: "Atlassian",
    kind: "Enterprise SaaS",
    oneLiner: "Jira, Confluence, Bitbucket — collaboration + dev-tools at scale.",
    overview: "Atlassian's India engineering centre is Bengaluru (newly expanded since 2022). Teams work across Jira, Confluence, Bitbucket, Compass, and the underlying platform. Atlassian is known for a strong remote-friendly culture and a values-based hiring process — behavioural rounds explicitly probe the Atlassian values (Open Company / No Bullshit, Don't #@!% the Customer, etc.). Engineering loops are 4-5 rounds with DSA + system design + values.",
    hqCity: "Sydney",
    hqCountry: "Australia",
    founded: 2002,
    careersUrl: "https://www.atlassian.com/company/careers/all-jobs?team=Engineering&location=India",
    indiaHubs: ["Bengaluru"],
    roleFunctions: ["backend", "frontend", "fullstack", "data_engineering", "ml_ai", "devops_platform", "product_management", "design"],
    typicalStack: ["Java", "Kotlin", "TypeScript", "React", "Kafka", "PostgreSQL", "AWS", "Kubernetes", "GraphQL"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "nvidia",
    name: "Nvidia",
    kind: "Big Tech",
    oneLiner: "GPUs, AI infrastructure, CUDA, robotics, automotive — the AI-era foundation.",
    overview: "Nvidia India has engineering centres in Bengaluru, Pune, Hyderabad, and Gurugram — historically anchored in GPU driver / SoC / automotive teams, expanding rapidly into AI software (NIM, NeMo, Triton) since 2023. Hiring loops emphasise deep technical depth in chosen domain (CUDA, computer graphics, ML systems) plus strong systems fundamentals. Compensation has risen sharply since 2023 alongside the AI demand wave.",
    hqCity: "Santa Clara, CA",
    hqCountry: "United States",
    founded: 1993,
    careersUrl: "https://www.nvidia.com/en-in/about-nvidia/careers/",
    indiaHubs: ["Bengaluru", "Pune", "Hyderabad", "Gurugram"],
    roleFunctions: ["backend", "ml_ai", "devops_platform", "data_engineering", "qa_sdet"],
    typicalStack: ["C++", "CUDA", "Python", "PyTorch", "TensorRT", "OpenGL", "Vulkan", "Linux kernel", "Triton", "NeMo"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "oracle",
    name: "Oracle",
    kind: "Enterprise SaaS",
    oneLiner: "Oracle DB, Cloud Infrastructure (OCI), NetSuite, Fusion ERP — enterprise software.",
    overview: "Oracle's India engineering presence is large across Bengaluru, Hyderabad, and Noida — working on Oracle Database, OCI (Oracle Cloud Infrastructure, the AWS-competitor), Fusion ERP, NetSuite, and the AI/Analytics stack. Hiring loops are standard 4-5 round product-co template; engineering culture emphasises stability + scale + enterprise rigour over startup velocity.",
    hqCity: "Austin, TX",
    hqCountry: "United States",
    founded: 1977,
    careersUrl: "https://careers.oracle.com/jobs/#en/sites/jobsearch/requisitions?location=India",
    indiaHubs: ["Bengaluru", "Hyderabad", "Noida"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Oracle DB", "PL/SQL", "OCI", "Kubernetes", "Python", "C++", "TypeScript", "Terraform"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    kind: "Enterprise SaaS",
    oneLiner: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau — CRM platform.",
    overview: "Salesforce India is anchored in Bengaluru and Hyderabad, working across the core Sales / Service / Marketing Clouds, Data Cloud, Einstein AI, Tableau and MuleSoft. Hiring loops follow the standard product-co template with extra emphasis on Salesforce 'V2MOM' + Trailblazer values. India teams contribute to global product surfaces, not India-only features.",
    hqCity: "San Francisco, CA",
    hqCountry: "United States",
    founded: 1999,
    careersUrl: "https://careers.salesforce.com/en/jobs/?location=India",
    indiaHubs: ["Bengaluru", "Hyderabad"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "product_management"],
    typicalStack: ["Java", "Apex", "Lightning Web Components", "TypeScript", "React", "Kubernetes", "AWS", "Python", "PostgreSQL"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "sap-labs",
    name: "SAP Labs",
    kind: "Enterprise SaaS",
    oneLiner: "S/4HANA, SuccessFactors, Concur, Ariba — enterprise resource planning at scale.",
    overview: "SAP Labs India is one of the largest SAP R&D centres outside Germany — Bengaluru is the primary location, with smaller presence in Gurugram and Mumbai. Engineering work spans S/4HANA, SuccessFactors, BTP (Business Technology Platform), and AI / ML embedded across the suite. The culture is enterprise + structured but globally connected — India teams ship for global SAP customers.",
    hqCity: "Walldorf",
    hqCountry: "Germany",
    founded: 1972,
    careersUrl: "https://jobs.sap.com/search/?locationsearch=India",
    indiaHubs: ["Bengaluru", "Gurugram", "Mumbai"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "ABAP", "JavaScript", "SAP HANA", "SAP UI5", "Kubernetes", "Python", "Node.js"],
    referenceBands: FAANG_BANDS,
  },
  {
    slug: "razorpay",
    name: "Razorpay",
    kind: "Fintech",
    oneLiner: "Payments, banking, payroll for businesses — India's leading product fintech.",
    overview: "Razorpay is India's leading product-led fintech, headquartered in Bengaluru with a large engineering team and growing presence in Singapore. Products span payment gateway (the original), payment links, RazorpayX (business banking), Razorpay Payroll, and lending. Engineering loops emphasise practical machine-coding rounds (build a small system in 90 minutes) over pure DSA puzzles, with strong payment-domain knowledge expected at senior levels.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2014,
    careersUrl: "https://razorpay.com/jobs/",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Go", "Python", "Java", "Kafka", "PostgreSQL", "Redis", "AWS", "Kubernetes", "MySQL", "Elasticsearch"],
    referenceBands: FINTECH_BANDS,
  },
  {
    slug: "phonepe",
    name: "PhonePe",
    kind: "Fintech",
    oneLiner: "UPI payments, financial services, PhonePe Switch, lending — India's largest UPI app.",
    overview: "PhonePe is India's largest UPI payment app by volume, headquartered in Bengaluru with engineering across Bengaluru and a growing Pune presence. Products span UPI payments (the core), wealth management, insurance, lending, and PhonePe Switch (a mini-app platform). Engineering loops emphasise distributed-systems at high RPS, idempotency, and on-call sensibility. Comp bands track Razorpay closely.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2015,
    careersUrl: "https://www.phonepe.com/careers/",
    indiaHubs: ["Bengaluru", "Pune"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Java", "Go", "Kafka", "Aerospike", "Cassandra", "AWS", "Kubernetes", "Python", "TypeScript"],
    referenceBands: FINTECH_BANDS,
  },
  {
    slug: "zerodha",
    name: "Zerodha",
    kind: "Fintech",
    oneLiner: "India's largest stockbroker — Kite, Console, Coin, Varsity.",
    overview: "Zerodha is India's largest retail stockbroker, famously profitable and known for an unconventional engineering culture — small teams, open-source first, no VC funding. Engineering is centred on Bengaluru with a smaller Hyderabad presence. Teams work across Kite (trading platform), Console (portfolio), Coin (mutual funds), and Varsity. Hiring loops are lean — typically 2-3 rounds focusing on practical engineering + GitHub portfolio over puzzle DSA.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2010,
    careersUrl: "https://zerodha.com/careers/",
    indiaHubs: ["Bengaluru", "Hyderabad"],
    roleFunctions: ["backend", "frontend", "fullstack", "mobile", "devops_platform", "data_engineering"],
    typicalStack: ["Go", "Python", "PostgreSQL", "Redis", "Vue.js", "React", "Linux", "Kafka", "Postgres"],
    referenceBands: FINTECH_BANDS,
  },
  {
    slug: "cred",
    name: "CRED",
    kind: "Fintech",
    oneLiner: "Premium credit-card management, payments, rewards, lending — India's design-first fintech.",
    overview: "CRED is a Bengaluru-headquartered fintech focused on the premium consumer segment — credit-card payments + rewards + lending + ecommerce. Engineering teams emphasise design quality, polish, and performance at scale. Hiring loops are 3-4 rounds with a strong design-sensibility component (even backend rounds occasionally probe product instincts). Comp is competitive within the India-unicorn band.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2018,
    careersUrl: "https://careers.cred.club/",
    indiaHubs: ["Bengaluru"],
    roleFunctions: ["backend", "frontend", "fullstack", "ml_ai", "mobile", "devops_platform", "design", "product_management"],
    typicalStack: ["Kotlin", "Java", "TypeScript", "React Native", "AWS", "Kubernetes", "PostgreSQL", "Redis", "Kafka"],
    referenceBands: INDIA_UNICORN_BANDS,
  },
  {
    slug: "groww",
    name: "Groww",
    kind: "Fintech",
    oneLiner: "Investing app for stocks, mutual funds, F&O, IPOs — direct-to-consumer wealth.",
    overview: "Groww is a Bengaluru-headquartered investing platform serving 20M+ retail investors across stocks, mutual funds, F&O, and IPOs. Engineering teams emphasise high-throughput consumer apps + regulatory + scale. Hiring loops are 3-4 rounds focused on DSA + system design + product instincts. Groww is known for relatively flat engineering bands compared to other India unicorns.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2017,
    careersUrl: "https://groww.in/careers",
    indiaHubs: ["Bengaluru"],
    roleFunctions: ["backend", "frontend", "fullstack", "ml_ai", "mobile", "devops_platform", "data_engineering", "product_management"],
    typicalStack: ["Java", "TypeScript", "React", "React Native", "Kotlin", "AWS", "PostgreSQL", "Redis", "Kafka"],
    referenceBands: INDIA_UNICORN_BANDS,
  },
  {
    slug: "swiggy",
    name: "Swiggy",
    kind: "Consumer-Tech",
    oneLiner: "Food delivery, Instamart (10-min grocery), Dineout, Genie — India's super-app for hyperlocal.",
    overview: "Swiggy is a Bengaluru-headquartered consumer-tech company operating food delivery, Instamart (10-min grocery), Dineout, and Genie. Engineering teams emphasise high-throughput consumer systems (200K+ RPS food orders), real-time ETA / surge / dispatch, and hyperlocal logistics. Hiring loops are 4-5 rounds with strong system-design emphasis on food-delivery-domain scenarios.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2014,
    careersUrl: "https://careers.swiggy.com/",
    indiaHubs: ["Bengaluru", "Gurugram", "Pune"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Java", "Go", "Python", "React", "React Native", "Kafka", "Cassandra", "AWS", "PostgreSQL", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS,
  },
  {
    slug: "zomato",
    name: "Zomato",
    kind: "Consumer-Tech",
    oneLiner: "Food delivery, Hyperpure (B2B supply), Blinkit (10-min grocery), dining — India's hyperlocal giant.",
    overview: "Zomato is a Gurugram-headquartered consumer-tech company operating food delivery, dining-out, Hyperpure (B2B restaurant supply), and Blinkit (10-min quick commerce). Engineering teams emphasise high-RPS consumer apps, real-time dispatch + ETA, search + discovery, and AI for menu / fraud / pricing. Hiring loops are 4-5 rounds with system design + behavioural emphasis.",
    hqCity: "Gurugram",
    hqCountry: "India",
    founded: 2008,
    careersUrl: "https://www.zomato.com/careers",
    indiaHubs: ["Gurugram", "Bengaluru", "Delhi NCR"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Go", "Java", "Python", "React", "React Native", "Kafka", "MySQL", "MongoDB", "AWS", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS,
  },
  {
    slug: "flipkart",
    name: "Flipkart",
    kind: "E-commerce",
    oneLiner: "E-commerce marketplace, Myntra (fashion), Cleartrip (travel) — India's largest online retailer.",
    overview: "Flipkart is a Bengaluru-headquartered e-commerce group (owned by Walmart) operating the core marketplace, Myntra (fashion), Cleartrip (travel), and Flipkart Health+. Engineering teams emphasise marketplace scale, search + discovery, pricing + promotions, supply-chain ML, and high-throughput consumer apps. Hiring loops are 4-5 rounds with strong DSA + system design.",
    hqCity: "Bengaluru",
    hqCountry: "India",
    founded: 2007,
    careersUrl: "https://www.flipkartcareers.com/",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Java", "Go", "Python", "React", "React Native", "Kafka", "MySQL", "Elasticsearch", "AWS", "Hadoop"],
    referenceBands: INDIA_UNICORN_BANDS,
  },
  // ─────────────────────────── Tier 1 expansion ───────────────────────────
  { slug: "adobe", name: "Adobe", kind: "Enterprise SaaS",
    oneLiner: "Creative Cloud, Document Cloud, Experience Cloud — creative + marketing software at global scale.",
    overview: "Adobe India has major engineering centres in Noida (largest outside US) and Bengaluru, working across Photoshop, Lightroom, Acrobat / PDF, Premiere, and the Experience Cloud marketing stack. India teams ship globally; loops emphasise strong CS fundamentals + design sensibility for creative-tool products.",
    hqCity: "San Jose, CA", hqCountry: "United States", founded: 1982,
    careersUrl: "https://careers.adobe.com/us/en/search-results?qcountry=India",
    indiaHubs: ["Noida", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["C++", "Java", "Python", "JavaScript", "React", "AWS", "Kubernetes", "ML", "PyTorch", "Tensorflow"],
    referenceBands: FAANG_BANDS },
  { slug: "intuit", name: "Intuit", kind: "Fintech",
    oneLiner: "TurboTax, QuickBooks, Credit Karma, Mailchimp — small-business + consumer fintech.",
    overview: "Intuit India is headquartered in Bengaluru, with engineering teams supporting QuickBooks, TurboTax, and the Mint/Credit Karma stack. India teams contribute to global products; the bar emphasises customer-obsessed engineering, ML-first product thinking, and finance-domain rigour.",
    hqCity: "Mountain View, CA", hqCountry: "United States", founded: 1983,
    careersUrl: "https://jobs.intuit.com/search-jobs/India",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Python", "React", "AWS", "Kubernetes", "Spark", "GraphQL", "TypeScript", "TensorFlow"],
    referenceBands: FAANG_BANDS },
  { slug: "uber", name: "Uber", kind: "Consumer-Tech",
    oneLiner: "Rides, Eats, Freight — global mobility + logistics marketplace.",
    overview: "Uber India has engineering centres in Bengaluru and Hyderabad with smaller Gurugram presence. Teams work on mobility (Uber + Uber Auto), Eats, and globally-shared platform services. Hiring loops emphasise distributed systems + dispatch algorithms + dynamic pricing.",
    hqCity: "San Francisco, CA", hqCountry: "United States", founded: 2009,
    careersUrl: "https://www.uber.com/global/en/careers/list/?location=IND",
    indiaHubs: ["Bengaluru", "Hyderabad", "Gurugram"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Go", "Java", "Python", "Kafka", "Cassandra", "Kubernetes", "Schemaless", "M3", "PyTorch", "React"],
    referenceBands: FAANG_BANDS },
  { slug: "paypal", name: "PayPal", kind: "Fintech",
    oneLiner: "Global payments + Braintree, Venmo, Honey — consumer + merchant fintech.",
    overview: "PayPal India has engineering centres in Chennai, Bengaluru, and Hyderabad working on payment infrastructure, fraud / risk, merchant onboarding, and Braintree. Loops emphasise distributed systems + financial correctness + on-call discipline.",
    hqCity: "San Jose, CA", hqCountry: "United States", founded: 1998,
    careersUrl: "https://paypal.eightfold.ai/careers?location=India",
    indiaHubs: ["Bengaluru", "Chennai", "Hyderabad"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Node.js", "React", "Kafka", "Cassandra", "GCP", "Kubernetes", "Python", "ML"],
    referenceBands: FAANG_BANDS },
  { slug: "servicenow", name: "ServiceNow", kind: "Enterprise SaaS",
    oneLiner: "Now Platform — IT service, workflow, HR, customer service automation.",
    overview: "ServiceNow India has a large Hyderabad engineering centre and growing Bengaluru presence. Teams work on the core Now Platform plus AI / agentic workflow products. Loops emphasise platform engineering + product instincts + workflow domain knowledge.",
    hqCity: "Santa Clara, CA", hqCountry: "United States", founded: 2003,
    careersUrl: "https://careers.servicenow.com/careers-home/jobs?country=India",
    indiaHubs: ["Hyderabad", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "JavaScript", "Angular", "AWS", "Kubernetes", "Python", "MySQL", "Elasticsearch"],
    referenceBands: FAANG_BANDS },
  { slug: "stripe", name: "Stripe", kind: "Fintech",
    oneLiner: "Payments infrastructure for the internet — billing, Atlas, Issuing, Identity.",
    overview: "Stripe India is a small but rapidly-growing engineering team (Bengaluru + remote) working on globally-deployed payment products. Hiring bar is exceptionally high — loops emphasise rigorous engineering + product taste + financial correctness.",
    hqCity: "San Francisco, CA", hqCountry: "United States", founded: 2010,
    careersUrl: "https://stripe.com/jobs/search?office_locations=India",
    indiaHubs: ["Bengaluru", "Remote-India"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Ruby", "Go", "TypeScript", "React", "Scala", "PostgreSQL", "Kafka", "AWS", "Python"],
    referenceBands: FAANG_BANDS },
  // ─────────────────────────── Tier 2 — Indian unicorns + SaaS ────────────
  { slug: "freshworks", name: "Freshworks", kind: "Enterprise SaaS",
    oneLiner: "Freshdesk, Freshservice, Freshchat — customer + employee support SaaS suite.",
    overview: "Freshworks is a Chennai-headquartered SaaS company (Nasdaq listed) with engineering across Chennai, Bengaluru, and Hyderabad. The product suite spans customer support, IT service management, sales CRM, and marketing automation. Loops are 3-4 rounds with practical engineering emphasis.",
    hqCity: "Chennai", hqCountry: "India", founded: 2010,
    careersUrl: "https://careers.freshworks.com/jobs",
    indiaHubs: ["Chennai", "Bengaluru", "Hyderabad"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Ruby on Rails", "Java", "Go", "Python", "Ember.js", "React", "MySQL", "Redis", "AWS"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "zoho", name: "Zoho", kind: "Enterprise SaaS",
    oneLiner: "Zoho One — 50+ business apps (CRM, Mail, Books, Projects) for SMBs.",
    overview: "Zoho is famously bootstrapped (no VC) and headquartered in Chennai with a major campus in Tenkasi (Tamil Nadu). 50+ products span CRM, productivity, finance, and developer tools. Engineering culture is unusual — long tenure, in-house-everything, profitable-from-day-one. Loops are practical, low-puzzle, code-portfolio-friendly.",
    hqCity: "Chennai", hqCountry: "India", founded: 1996,
    careersUrl: "https://careers.zohocorp.com/jobs/Careers",
    indiaHubs: ["Chennai", "Bengaluru", "Tenkasi"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "JavaScript", "C++", "MySQL", "Cassandra", "Kafka", "Redis", "Python", "AWS"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "postman", name: "Postman", kind: "Enterprise SaaS",
    oneLiner: "API platform — design, test, document, monitor APIs at scale.",
    overview: "Postman is a Bengaluru-headquartered API platform (HQ moved to San Francisco for capital reasons; engineering is largely India). Used by 30M+ developers globally. Teams emphasise developer-tools quality, performance, and product-design polish.",
    hqCity: "San Francisco, CA", hqCountry: "United States", founded: 2014,
    careersUrl: "https://www.postman.com/company/careers/open-positions/",
    indiaHubs: ["Bengaluru", "Remote-India"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Node.js", "TypeScript", "React", "Electron", "Go", "PostgreSQL", "AWS", "Kafka", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "browserstack", name: "BrowserStack", kind: "Enterprise SaaS",
    oneLiner: "Cloud-based cross-browser + real-device testing platform.",
    overview: "BrowserStack is a Mumbai-headquartered SaaS company providing real-device + cross-browser testing infrastructure. Engineering split between Mumbai and Bengaluru with a profitable, bootstrap-style culture. Loops emphasise systems engineering + product depth.",
    hqCity: "Mumbai", hqCountry: "India", founded: 2011,
    careersUrl: "https://www.browserstack.com/careers",
    indiaHubs: ["Mumbai", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Ruby", "Rails", "Go", "JavaScript", "React", "AWS", "Kubernetes", "MySQL", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "chargebee", name: "Chargebee", kind: "Enterprise SaaS",
    oneLiner: "Subscription billing + revenue operations for SaaS, e-commerce, and services.",
    overview: "Chargebee is a Chennai-headquartered SaaS company focused on subscription billing + recurring revenue. Engineering teams in Chennai and Bengaluru. Loops emphasise billing-domain depth + system reliability for financial-correctness use cases.",
    hqCity: "Chennai", hqCountry: "India", founded: 2011,
    careersUrl: "https://www.chargebee.com/careers/open-positions/",
    indiaHubs: ["Chennai", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Ruby", "JavaScript", "React", "AWS", "PostgreSQL", "Kafka", "Redis", "Kubernetes"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "meesho", name: "Meesho", kind: "E-commerce",
    oneLiner: "Social commerce platform connecting small resellers + Tier 2/3 buyers.",
    overview: "Meesho is a Bengaluru-headquartered social commerce platform serving 100M+ users primarily in Tier 2/3 India. Engineering emphasises high-RPS consumer apps, vernacular UX, fraud / quality systems, and supply-chain ML.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2015,
    careersUrl: "https://www.meesho.io/careers/open-jobs",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Java", "Kotlin", "Go", "Python", "Kafka", "Redis", "AWS", "PostgreSQL", "React Native"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "nykaa", name: "Nykaa", kind: "E-commerce",
    oneLiner: "Beauty + fashion e-commerce — own brands + multi-brand retailer.",
    overview: "Nykaa is a Mumbai-headquartered beauty + fashion e-commerce company. Engineering in Mumbai and Bengaluru with consumer + retail tech teams. Loops emphasise consumer engineering + recommendation + content + supply-chain.",
    hqCity: "Mumbai", hqCountry: "India", founded: 2012,
    careersUrl: "https://www.nykaa.com/careers/jobs",
    indiaHubs: ["Mumbai", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Node.js", "React", "Python", "MongoDB", "AWS", "Redis", "Kafka", "Java"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "dream11", name: "Dream11", kind: "Consumer-Tech",
    oneLiner: "Fantasy sports — cricket, kabaddi, football fantasy contests at scale.",
    overview: "Dream11 is a Mumbai-headquartered fantasy sports company serving 150M+ users with extreme peak load during match windows. Engineering emphasises real-time leaderboards, fraud detection, and elastic scale. Loops focus on systems + low-latency design.",
    hqCity: "Mumbai", hqCountry: "India", founded: 2008,
    careersUrl: "https://careers.dream11.com/jobs",
    indiaHubs: ["Mumbai"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Java", "Scala", "Kotlin", "Go", "Kafka", "Cassandra", "Aerospike", "AWS", "React"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "policybazaar", name: "PolicyBazaar", kind: "Fintech",
    oneLiner: "Insurance aggregator — health, motor, life, travel insurance comparison + sale.",
    overview: "PolicyBazaar (PB Fintech) is a Gurugram-headquartered insurance + lending aggregator listed on Indian stock exchanges. Engineering across Gurugram and Mumbai. Loops emphasise consumer engineering + lead-to-purchase funnels + regulatory awareness.",
    hqCity: "Gurugram", hqCountry: "India", founded: 2008,
    careersUrl: "https://www.policybazaar.com/careers/jobs",
    indiaHubs: ["Gurugram", "Mumbai"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: [".NET", "Node.js", "React", "Angular", "MySQL", "MongoDB", "AWS", "Redis"],
    referenceBands: FINTECH_BANDS },
  { slug: "lenskart", name: "Lenskart", kind: "E-commerce",
    oneLiner: "Eyewear D2C — online + 1,500+ retail stores across India + global expansion.",
    overview: "Lenskart is a Gurugram-headquartered eyewear D2C brand operating online + offline at massive scale. Engineering across Gurugram and Bengaluru. Recently expanded internationally (SEA, Middle East). Loops emphasise consumer engineering + AR try-on + supply-chain.",
    hqCity: "Gurugram", hqCountry: "India", founded: 2010,
    careersUrl: "https://careers.lenskart.com/",
    indiaHubs: ["Gurugram", "Bengaluru", "Delhi NCR"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Node.js", "React", "React Native", "Python", "Java", "MongoDB", "AWS", "Kubernetes"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "udaan", name: "Udaan", kind: "E-commerce",
    oneLiner: "B2B commerce — wholesale marketplace connecting kirana stores with manufacturers.",
    overview: "Udaan is a Bengaluru-headquartered B2B commerce platform connecting small retailers (kiranas) with manufacturers + wholesalers across categories. Engineering emphasises marketplace dynamics + credit + logistics at India-deep-distribution scale.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2016,
    careersUrl: "https://udaan.com/career.html",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Go", "Kotlin", "Python", "Kafka", "MySQL", "PostgreSQL", "AWS", "React"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "delhivery", name: "Delhivery", kind: "Consumer-Tech",
    oneLiner: "Third-party logistics — supply-chain, last-mile, warehousing, freight for e-commerce.",
    overview: "Delhivery is a Gurugram-headquartered logistics + supply-chain company (publicly listed). Engineering across Gurugram and Bengaluru. Loops emphasise systems engineering for logistics — ETAs, dispatch, optimization, warehouse automation.",
    hqCity: "Gurugram", hqCountry: "India", founded: 2011,
    careersUrl: "https://www.delhivery.com/careers/",
    indiaHubs: ["Gurugram", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Python", "Java", "Go", "PostgreSQL", "Kafka", "AWS", "ML", "TypeScript", "React"],
    referenceBands: INDIA_UNICORN_BANDS },
  // ─────────────────────────── Tier 3 — emerging & solid ──────────────────
  { slug: "sharechat", name: "ShareChat", kind: "Consumer-Tech",
    oneLiner: "Vernacular social media + short-video (Moj) for India's regional language users.",
    overview: "ShareChat is a Bengaluru-headquartered vernacular social media + short-video app (Moj). Engineering emphasises high-RPS consumer apps, vernacular content moderation, recommendation ML, and elastic infra.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2015,
    careersUrl: "https://sharechat.com/careers",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Go", "Java", "Python", "Kotlin", "Kafka", "Cassandra", "Redis", "AWS", "GCP", "PyTorch"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "ola", name: "Ola", kind: "Consumer-Tech",
    oneLiner: "Ride-hailing + Ola Electric (scooters, cars), Krutrim (AI) — mobility + EV + AI.",
    overview: "Ola is a Bengaluru-headquartered mobility company with engineering spanning ride-hailing, Ola Electric (vehicles + manufacturing tech), and Krutrim (AI / LLMs). Engineering across Bengaluru with high focus on mobility platforms + EV systems + ML.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2010,
    careersUrl: "https://olacabs.com/careers",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management", "design"],
    typicalStack: ["Java", "Scala", "Go", "Python", "Kafka", "Cassandra", "AWS", "PyTorch", "React"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "paytm", name: "Paytm", kind: "Fintech",
    oneLiner: "UPI, wallet, merchant payments, broking, lending — India's diversified fintech.",
    overview: "Paytm (One97 Communications) is a Noida-headquartered fintech listed on Indian stock exchanges. Engineering across Noida, Bengaluru, and Mumbai. Loops emphasise distributed systems + regulatory + financial domain knowledge.",
    hqCity: "Noida", hqCountry: "India", founded: 2010,
    careersUrl: "https://jobs.paytm.com/",
    indiaHubs: ["Noida", "Bengaluru", "Mumbai"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Kotlin", "Python", "Node.js", "MySQL", "Cassandra", "Kafka", "AWS", "React"],
    referenceBands: FINTECH_BANDS },
  { slug: "inmobi", name: "InMobi", kind: "Enterprise SaaS",
    oneLiner: "Mobile advertising + Glance (lock-screen content) — ad-tech at consumer scale.",
    overview: "InMobi is a Bengaluru-headquartered ad-tech company with engineering across Bengaluru and Gurugram. Products span mobile advertising platform + Glance (lock-screen content + Roposo short video). Loops emphasise distributed systems + ML + real-time bidding.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2007,
    careersUrl: "https://www.inmobi.com/company/careers/",
    indiaHubs: ["Bengaluru", "Gurugram"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Scala", "Go", "Python", "Kafka", "Cassandra", "Druid", "AWS", "TensorFlow"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "unacademy", name: "Unacademy", kind: "Consumer-Tech",
    oneLiner: "EdTech — live + on-demand classes for UPSC, JEE, NEET, banking exams.",
    overview: "Unacademy is a Bengaluru-headquartered EdTech company focused on competitive-exam preparation. Engineering emphasises live-video streaming at scale + content + interactive practice + recommendation.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2015,
    careersUrl: "https://unacademy.com/careers",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Python", "Node.js", "React", "React Native", "Kotlin", "Swift", "AWS", "PostgreSQL", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "cars24", name: "Cars24", kind: "E-commerce",
    oneLiner: "Used-car marketplace — buy / sell / finance with pickup + delivery.",
    overview: "Cars24 is a Gurugram-headquartered used-car marketplace with online + offline ops, finance, and inventory management. Engineering across Gurugram and Bengaluru. Loops emphasise consumer engineering + pricing ML + auction systems.",
    hqCity: "Gurugram", hqCountry: "India", founded: 2015,
    careersUrl: "https://www.cars24.com/careers/",
    indiaHubs: ["Gurugram", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Node.js", "Python", "Java", "React", "React Native", "MySQL", "AWS", "Kafka"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "myntra", name: "Myntra", kind: "E-commerce",
    oneLiner: "Fashion e-commerce — apparel, footwear, accessories, beauty (Flipkart Group).",
    overview: "Myntra is a Bengaluru-headquartered fashion e-commerce platform, part of the Flipkart Group (Walmart). Engineering emphasises fashion-specific catalog + sizing + visual search + personalisation. Loops follow Flipkart-style 4-5 round structure.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2007,
    careersUrl: "https://careers.myntra.com/",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Java", "Go", "Python", "React", "React Native", "Kafka", "MySQL", "Elasticsearch", "AWS"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "practo", name: "Practo", kind: "Consumer-Tech",
    oneLiner: "HealthTech — doctor search, teleconsult, clinic management, online medicines.",
    overview: "Practo is a Bengaluru-headquartered HealthTech company spanning consumer health, teleconsultation, and clinic-management SaaS. Engineering emphasises healthcare-domain regulatory + reliability + consumer engineering.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2008,
    careersUrl: "https://www.practo.com/company/careers",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Node.js", "Python", "React", "React Native", "MongoDB", "PostgreSQL", "AWS", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "pine-labs", name: "Pine Labs", kind: "Fintech",
    oneLiner: "Merchant payment terminals, EMI infrastructure, prepaid + working-capital lending.",
    overview: "Pine Labs is a Noida-headquartered merchant fintech operating 9 lakh+ POS terminals across India + SEA. Engineering across Noida and Bengaluru. Loops emphasise payment infra + fraud + merchant analytics.",
    hqCity: "Noida", hqCountry: "India", founded: 1998,
    careersUrl: "https://www.pinelabs.com/careers",
    indiaHubs: ["Noida", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Python", ".NET", "React", "Kafka", "PostgreSQL", "AWS", "Redis"],
    referenceBands: FINTECH_BANDS },
  { slug: "nobroker", name: "NoBroker", kind: "Consumer-Tech",
    oneLiner: "No-brokerage real estate — rent, buy, sell, home services.",
    overview: "NoBroker is a Bengaluru-headquartered real-estate tech platform with consumer + service-marketplace engineering. Emphasises lead-to-rent funnels + ML for fraud + home-service operations.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2014,
    careersUrl: "https://www.nobroker.in/careers",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Java", "Python", "Node.js", "React", "React Native", "MongoDB", "AWS", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "wingify", name: "Wingify", kind: "Enterprise SaaS",
    oneLiner: "VWO — A/B testing, experimentation, behavioural analytics SaaS.",
    overview: "Wingify (VWO) is a Delhi-headquartered bootstrap-funded SaaS company providing A/B testing + experimentation + behavioural analytics platforms. Engineering is small, profitable, remote-friendly.",
    hqCity: "Delhi", hqCountry: "India", founded: 2009,
    careersUrl: "https://wingify.com/careers/",
    indiaHubs: ["Delhi NCR", "Remote-India"],
    roleFunctions: [...COMMON_ROLES, "design"],
    typicalStack: ["Node.js", "TypeScript", "React", "Python", "MongoDB", "PostgreSQL", "AWS", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "clevertap", name: "CleverTap", kind: "Enterprise SaaS",
    oneLiner: "Mobile marketing + customer engagement + analytics for consumer apps.",
    overview: "CleverTap is a Mumbai-headquartered SaaS company providing customer-engagement infrastructure to consumer apps globally. Engineering in Mumbai and Bengaluru. Loops emphasise scale (events ingestion at billions/day) + ML personalisation.",
    hqCity: "Mumbai", hqCountry: "India", founded: 2013,
    careersUrl: "https://clevertap.com/careers/",
    indiaHubs: ["Mumbai", "Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Go", "Java", "Python", "Kafka", "Cassandra", "ClickHouse", "AWS", "React"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "moengage", name: "MoEngage", kind: "Enterprise SaaS",
    oneLiner: "Customer engagement platform — mobile + web push, email, in-app, journeys.",
    overview: "MoEngage is a Bengaluru-headquartered SaaS company providing AI-driven customer engagement infrastructure. Engineering emphasises events pipeline at scale + ML for predictive segmentation + delivery channels.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2014,
    careersUrl: "https://www.moengage.com/about-us/careers/",
    indiaHubs: ["Bengaluru"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Go", "Java", "Scala", "Python", "Kafka", "Spark", "AWS", "PostgreSQL", "Redis"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "yellow-ai", name: "Yellow.ai", kind: "Enterprise SaaS",
    oneLiner: "Conversational AI + agentic platform for customer + employee experience.",
    overview: "Yellow.ai is a Bengaluru-headquartered conversational AI + agentic SaaS platform. Engineering emphasises LLM agents + multi-channel integration (voice, chat, email) + enterprise security.",
    hqCity: "Bengaluru", hqCountry: "India", founded: 2016,
    careersUrl: "https://yellow.ai/careers/",
    indiaHubs: ["Bengaluru", "Remote-India"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Node.js", "Python", "TypeScript", "React", "AWS", "MongoDB", "Kafka", "Redis", "LangChain"],
    referenceBands: INDIA_UNICORN_BANDS },
  { slug: "arcesium", name: "Arcesium", kind: "Fintech",
    oneLiner: "Capital-markets technology — middle/back-office for hedge funds, asset managers, banks.",
    overview: "Arcesium is a Bengaluru + Hyderabad-headquartered capital-markets fintech (founded by D. E. Shaw + Blackstone). Engineering across Bengaluru and Hyderabad. Loops emphasise rigorous engineering + finance-domain depth + on-call sensibility.",
    hqCity: "New York / Bengaluru", hqCountry: "United States", founded: 2015,
    careersUrl: "https://www.arcesium.com/careers",
    indiaHubs: ["Bengaluru", "Hyderabad"],
    roleFunctions: [...COMMON_ROLES, "engineering_management"],
    typicalStack: ["Java", "Python", "Scala", "PostgreSQL", "Kafka", "AWS", "Spark", "TypeScript", "React"],
    referenceBands: FINTECH_BANDS },
];

export function companyFactsBySlug(slug: string): CompanyFacts | null {
  return COMPANY_FACTS.find((c) => c.slug === slug) ?? null;
}

/** Companies that publicly operate engineering in the given hub. */
export function companiesInHub(hub: string): CompanyFacts[] {
  return COMPANY_FACTS.filter((c) => c.indiaHubs.includes(hub));
}

/** Companies that hire for the given canonical role function. */
export function companiesForRole(role: CanonicalRoleFunction): CompanyFacts[] {
  return COMPANY_FACTS.filter((c) => c.roleFunctions.includes(role));
}

/** Companies whose typical stack mentions a token matching the skill name or its aliases. */
export function companiesForSkill(skillAliases: string[]): CompanyFacts[] {
  const lower = skillAliases.map((a) => a.toLowerCase());
  return COMPANY_FACTS.filter((c) =>
    c.typicalStack.some((s) => lower.some((a) => s.toLowerCase().includes(a) || a.includes(s.toLowerCase()))),
  );
}
